# https://taskfile.dev

version: '3'

vars:
  PROJECT_NAME: Dyna Bank
  BIN: dyna_bank

tasks:
  build:
    cmds:
      - echo "Building {{.PROJECT_NAME}}"
      - go build -o ./bin/{{.BIN}} ./internal/cmd/server
    silent: true
  run:
    cmds:
      - echo "Executing {{.PROJECT_NAME}} in developent mode"
      - air
    silent: true
  pg_dump:
    cmds:
      - pg_dump -s -t 'application.*' -d dyna_bank -U dyna_bank_admin  > ./internal/db/create_tables.sql
    silent: true

